nlesc-nano/flamingo

flamingo/properties.py
`extract_optimized_geometry` would previously assume that only a single molecule was stored in the `ligand/atoms` dataset, and would in most cases produce an invalid .xyz file otherwise [1].
This PR remedies aforementioned issue by addition of the `index` keyword, the latter referring to molecule's index within the dataset.
[1] All molecules would be concatenated into a single molecule within an .xyz file. If any padding was involved (due to different numbers of atoms per mol) than certain atomic symbols would be empty strings as well.
=> Ensure that only a single geometry is extracted by `extract_optimized_geometry`

README.rst, docs/tutorial_screening.rst, flamingo/cat_interface.py, flamingo/schemas.py, flamingo/screen.py, tests/test_cat_interface.py, tests/test_filter.py
Introduced new [CAT bulkiness parameters](https://cat.readthedocs.io/en/latest/4_optional.html#optional.qd.bulkiness)
=> Add new CAT bulkiness parameters

flamingo/screen.py
Gracefully exit the application if there are not more molecules to filter
=> add a message if there are not molecules to filter

setup.py
=> add init files in the data folders

flamingo/cat_interface.py, flamingo/schemas.py, tests/test_filter.py
=> solved #15

docs/tutorial_screening.rst, flamingo/screen.py, tests/files/input_test_filter.yml, tests/files/smiles_functional_groups.csv, tests/test_filter.py
Solved #18 by using smarts to filter the functional groups
=> Use SMARTS to filter

flamingo/cat_interface.py, flamingo/schemas.py, tests/test_filter.py
Remove the `d` option from [CAT bulkiness](https://cat.readthedocs.io/en/latest/4_optional.html?highlight=cosmo#optional.qd.bulkiness)
=> removed CAT d bulkiness option

flamingo/utils.py
=> Fix Boost error

flamingo/cat_interface.py
##change
* Use absolute path to core for CAT's input
=> used absolute path to core

flamingo/cat_interface.py, setup.py
Use [CAT thread safe](https://cat.readthedocs.io/en/latest/4_optional.html#optional.database.thread_safe) option to avoid a race condition
=> Use CAT thread safe option

flamingo/screen.py, setup.py
* Continue if there is an error reading CAT's output for small batches
* Merge all the results into a single file
=> fix small size batch issue and merge results

flamingo/cat_interface.py, flamingo/schemas.py, flamingo/screen.py
* Remove the `batches_size` and `threads` options from the input.
*  Use all the available CPU using [imap unordered](https://docs.python.org/3/library/multiprocessing.html#multiprocessing.pool.Pool.imap_unordered)
=> remove batches from input and use all the available CPUs

flamingo/screen.py
* solve #33  by restarting from last computed batch
=> restart from last batch

CHANGELOG.rst, README.rst, flamingo/schemas.py, flamingo/screen.py, tests/test_filter.py
* fix #38 
* Add a new  Keyword `parallel` (default=True) to run all the filters in parallel
=> run molecular filters in parallel #38

flamingo/schemas.py, flamingo/screen.py, tests/files/input_test_filter.yml, tests/test_featurizer.py, tests/test_filter.py
* Fix #43 
* Add `groups` and `maximum` keywords
* Remove single anchor filter
=> implement a filter for maximum number of functional groups

CHANGELOG.rst, flamingo/screen.py, tests/files/smiles_multiple_groups.csv, tests/test_filter.py
* Extend the support functional groups to filter #43
=> add more functional groups to the single functional group filter

flamingo/screen.py, tests/files/smiles_multiple_groups.csv
=> Create single functional group filter

flamingo/features/featurizer.py, tests/test_featurizer.py
=> Skip bond calculation as a feature

flamingo/screen.py
* Reset the indices after applying each filter
* Solved #59
=> Reset the molecular index when computing the druglikeness

flamingo/cat_interface.py
Manage the Smiles parallelization of Cosmo-RS from edit flamingo
=> run fast sigma using a single Core
